-- =============================================================
-- Migrations 005 + 006 — PostgreSQL version
-- 005: activity_log + work hours in settings
-- 006: departments + employee department/status
-- =============================================================
BEGIN;

-- 005: جدول سجل نشاط المدير (Audit Log)
CREATE TABLE IF NOT EXISTS activity_log (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id    integer DEFAULT NULL,
    action      varchar(80) NOT NULL,
    entity_type varchar(40) DEFAULT NULL,
    entity_id   integer DEFAULT NULL,
    details     text DEFAULT NULL,
    ip_address  varchar(45) DEFAULT NULL,
    created_at  timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_activity_created ON activity_log (created_at);
CREATE INDEX IF NOT EXISTS idx_activity_admin ON activity_log (admin_id);

-- 005: إعدادات أوقات الدوام
ALTER TABLE settings ADD COLUMN IF NOT EXISTS work_start time NOT NULL DEFAULT '08:00:00';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS work_end   time NOT NULL DEFAULT '17:00:00';

-- 006: جدول الأقسام
CREATE TABLE IF NOT EXISTS departments (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(100) NOT NULL UNIQUE,
    description varchar(255) NULL,
    created_at  timestamp DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO departments (name) VALUES
    ('الإدارة العامة'),
    ('الموارد البشرية'),
    ('المالية والمحاسبة'),
    ('تقنية المعلومات'),
    ('العمليات والخدمات')
ON CONFLICT (name) DO NOTHING;

-- 006: حقلا القسم والحالة للموظفين
ALTER TABLE employees ADD COLUMN IF NOT EXISTS department_id integer NULL REFERENCES departments(id) ON DELETE SET NULL;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS status varchar(20) NOT NULL DEFAULT 'active'
    CHECK (status IN ('active','inactive','terminated'));

COMMIT;
